### ISSUE TITLE
Binary missing `.exe` on Windows

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station-massa-node-manager#12]
**Describe the bug**
On Windows, the available binary isn't in the `.exe` format required by Windows.

**To Reproduce**

1. Download the v0.0.1 archive from Releases
2. Open the archive
3. See that the binary doesn't have a `.exe`

**Expected behavior**
The binary should `.exe`

**Thyra version**
Latest version on main

**Desktop:**
 - OS: Windows

**Comment by Thykof** [comment]
@peterjah did you fix this issue?

**Comment by thomas-senechal** [comment]
Closing since it has been fixed
