### ISSUE TITLE
Update node manager manifest

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-node-manager#59]
change name and add correct description + add new logo

Expected: 
    "author" : "Massa Labs",
    "name" : "Massa Node-manager",
    "description" : "Join Massa network now. Automatically install, configure and manage Massa nodes",

**Comment by SlnPons** [comment]
Additional questions: 
* What's the current logo? 
* How does the version is updated? 
* What are we supposed to have in Home? Is it normal that it is empty?
* And finally what are the existing tests about the manisfest on this repo? 
(It seems that we have diff tests on diff repo regarding the manifest....)

**Comment by pivilartisant** [comment]
the version is manually updated

**Comment by pivilartisant** [comment]
No tests are ran in this manifest.json

**Comment by pivilartisant** [comment]
@SlnPons the logo you gave is a png can you change it for a svg :)

**Comment by SlnPons** [comment]
my bad, here it is @pivilartisant 
![A1 svg](https://github.com/massalabs/station-massa-node-manager/assets/109611779/67d62f30-d2c8-4438-a4ea-e3686cc49479)
